export const WORDS = [
  'ace', 'aim', 'air', 'ant', 'arc', 'ash', 'axe', 'bad', 'bag', 'ban',
  'bar', 'bat', 'bay', 'beam', 'bear', 'beat', 'bell', 'bend', 'bird',
  'bite', 'blast', 'blink', 'block', 'blue', 'boat', 'bolt', 'boom',
  'brave', 'brick', 'bring', 'brush', 'bulk', 'burn', 'camp', 'card',
  'cat', 'chain', 'chart', 'chase', 'chip', 'clap', 'clash', 'climb',
  'cloud', 'code', 'coin', 'cold', 'comet', 'core', 'crane', 'crash',
  'crawl', 'crown', 'dash', 'deck', 'deep', 'dice', 'dive', 'door',
  'draft', 'drift', 'drill', 'drone', 'drop', 'dust', 'eagle', 'earth',
  'edge', 'ember', 'fair', 'fall', 'fang', 'farm', 'fast', 'fat',
  'field', 'fire', 'fish', 'flare', 'flash', 'fleet', 'flow', 'foam',
  'focus', 'forge', 'fox', 'frame', 'frost', 'game', 'gate', 'gear',
  'ghost', 'glow', 'gold', 'grid', 'guard', 'hail', 'hand', 'hawk',
  'heat', 'hero', 'hill', 'hive', 'hook', 'hope', 'iron', 'jazz',
  'jet', 'jump', 'keen', 'king', 'kite', 'laser', 'leaf', 'light',
  'line', 'lock', 'logic', 'lucky', 'mage', 'mark', 'maze', 'metal',
  'mint', 'moon', 'nova', 'orbit', 'pace', 'pack', 'path', 'peak',
  'pilot', 'pixel', 'plant', 'prime', 'pulse', 'quest', 'quick', 'rain',
  'rally', 'range', 'rapid', 'raven', 'rift', 'rise', 'river', 'rocket',
  'round', 'rush', 'sand', 'scale', 'scout', 'shade', 'shaft', 'sharp',
  'shell', 'shift', 'shine', 'shock', 'signal', 'skill', 'sky', 'slam',
  'slide', 'smoke', 'snap', 'solar', 'spark', 'speed', 'spell', 'spike',
  'spin', 'stack', 'star', 'steel', 'stone', 'storm', 'strike', 'swing',
  'tank', 'team', 'thorn', 'thunder', 'tide', 'tower', 'trace', 'trail',
  'trick', 'trust', 'turbo', 'vault', 'venom', 'wave', 'wind', 'wire',
  'wolf', 'zone',
];
